### PR TITLE
bug fixed in lib/react-drawer.css

### PR DESCRIPTION
**Pull request by AsafBrieferyDev**
This PR fixes a bug in  lib/react-drawer.css.
There was extra text that should not have been there making the import of the css crash.

### CODE REVIEW

**Comment by atom2ueki** [comment]
@AsafBrieferyDev thanks for the PR, I will review ASAP when I'm free, see if you got any time @jmfrancois ?

**Comment by atom2ueki** [comment]
@AsafBrieferyDev all the things from lib was a output from src, so `drawer.css` is the one generated by `ReactDrawer.scss`, if any thing make your  import of css crash, please modify `ReactDrawer.scss` from src instead of `drawer.css` from lib, I'd like to see the crash message if you still keep one

**Comment by turnerniles** [comment]
@atom2ueki I have the same issue. I'll take a look at the scss file.

Module build failed: Unknown word.

screen shot 2017-09-10 at 8 58 09 pm

**Comment by turnerniles** [comment]
@AsafBrieferyDev's fix works but I'm not sure why. And I'm not sure how to fix the issue since it seems to be an issue related to webpack processing animate.css which your setup handles fine because you have it as a global. @jmfrancois thoughts?

**Comment by nsberrow** [comment]
This fix isn't present in the latest npm install, once I copied and pasted the new css from here it worked. I think it's a minify issue of some sort.

**Comment by Sangeli** [comment]
Looks like the issue with the CSS isn't fixed for me when I just installed it today.

**Comment by atom2ueki** [comment]
this one have been fixed with latest build v1.3.0

**Pull request closed without merging**
